### ISSUE TITLE
Method can be created for function type but what is best usecase for this?

### ISSUE THREAD

**Issue by prithvipal** [abhishek-mane/golang-learning#1]
We can create a type of function as below:
```
type myFuncType = func(a, b string) string
type myfun myFuncType
```
Also, we can create a method to any type including function type:

```
func (m myfun) m1() {
	fmt.Println("Hey!!!")
	s := m("Ram", "Shyam")
	fmt.Println(s)
}
```

We can call `m1` method by on variable of `myfun` type.

```
func main() {
	var fn myfun
	fn = func(a, b string) string {
		return fmt.Sprintf("Hi %s and %s, How are you", a, b)
	}
	fn.m1()
}
```

But my question is, What could be the real time example where method to function type will be created?

**Comment by samtholiya** [comment]
`

    type A func(int, int) int
    
    func (a A) preCheck(param1 int, param2 int) (int, error) {
    	if param2 == 0 {
    		return 0, errors.New("Cannot Divide by zero")
    	}
    	return a(param1, param2), nil
    }
    
    func divideNumber(a int, b int) int {
    	return a / b
    }
    
    func main() {
    	var a A
    	a = divideNumber
    
    	ans, err := a.preCheck(32, 2)
    	fmt.Println(ans, err)
    	ans, err = a.preCheck(32, 0)
    	fmt.Println(ans, err)
    }

`
As seen in above case suppose we are having a function which takes func as a param so instead of every developer having to implement validation of the params we can always use that func with its method.
@Prithvipal .
